-- Now create the snowpipe
CREATE OR REPLACE PIPE SCD1_DB.PUBLIC.SCD1_PIPE
AUTO_INGEST = TRUE AS
COPY INTO SCD1_DB.PUBLIC.CUSTOMER_SOURCE
FROM
(
SELECT
$1 AS CUSTOMERNAME,
$2 AS PHONE,
$3 ASADDRESSLINE1,
$4 AS ADDRESSLINE2,
$5 AS CITY,
$6 AS STATE,
$7 AS POSTALCODE,
$8 AS COUNTRY,
$9 AS TERRITORY,
$10 AS CONTACTFIRSTNAME,
$11 AS CONTACTLASTNAME
FROM @SCD1_DB.PUBLIC.SCD1_STAGE)
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

-- Verify that the pipe was created and is running
SELECT SYSTEM$PIPE_STATUS('SCD1_DB.PUBLIC.SCD1_PIPE');

-- Show pipes to get the SQS ARN and create the event in the S3 bucket
SHOW PIPES;
